--
-- WriteFreely schema for PostgreSQL.
--
-- Unlike schema.sql and sqlite.sql, which describe the V1 schema and rely on
-- migrations V2 onwards to bring it up to date, this file describes the whole
-- schema as it stands after migration V18. `writefreely db init` runs it in a
-- single transaction and records V18 in appmigrations, so a Postgres database
-- never runs migrations V1 to V18. Migrations from V19 on run on every engine.
--
-- It was translated from the table definitions MariaDB reports for a
-- database built by `db init` (schema.sql plus every migration), with these
-- rules:
--
--   char(n)                    -> varchar(n), because Postgres pads char(n)
--   tinyint(1) used as a flag  -> boolean
--   any other tinyint          -> smallint
--   int(n), int(n) unsigned    -> integer
--   AUTO_INCREMENT             -> integer GENERATED BY DEFAULT AS IDENTITY
--   datetime, timestamp        -> timestamptz
--   binary, varbinary, blob    -> bytea
--   text, mediumtext           -> text
--
-- and a few varchar columns widened to text where MySQL would silently have
-- truncated a long value but Postgres raises an error instead.
--
-- Statements are separated by a semicolon at the end of a line, which is how
-- adminInitDatabase splits this file. Do not put one inside a comment.
--

CREATE TABLE accesstokens (
  token bytea NOT NULL,
  user_id integer NOT NULL,
  sudo boolean NOT NULL DEFAULT false,
  one_time boolean NOT NULL DEFAULT false,
  created timestamptz NOT NULL DEFAULT now(),
  expires timestamptz DEFAULT NULL,
  user_agent varchar(255) DEFAULT NULL,
  PRIMARY KEY (token)
);

CREATE TABLE appcontent (
  id varchar(36) NOT NULL,
  content text NOT NULL,
  updated timestamptz NOT NULL DEFAULT now(),
  title varchar(255) DEFAULT NULL,
  content_type varchar(36) NOT NULL DEFAULT 'page',
  PRIMARY KEY (id)
);

CREATE TABLE appmigrations (
  version integer NOT NULL,
  migrated timestamptz NOT NULL,
  result text NOT NULL
);

-- value is text: the fork stores newline-joined verification links here.
CREATE TABLE collectionattributes (
  collection_id integer NOT NULL,
  attribute varchar(128) NOT NULL,
  value text NOT NULL,
  PRIMARY KEY (collection_id, attribute)
);

CREATE TABLE collectionkeys (
  collection_id integer NOT NULL,
  public_key bytea NOT NULL,
  private_key bytea NOT NULL,
  PRIMARY KEY (collection_id)
);

CREATE TABLE collectionpasswords (
  collection_id integer NOT NULL,
  password varchar(60) NOT NULL,
  PRIMARY KEY (collection_id)
);

CREATE TABLE collectionredirects (
  prev_alias varchar(100) NOT NULL,
  new_alias varchar(100) NOT NULL,
  PRIMARY KEY (prev_alias)
);

-- privacy is a bit field, not a flag, so it is smallint.
CREATE TABLE collections (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  alias varchar(100) DEFAULT NULL,
  title varchar(255) NOT NULL,
  description varchar(160) NOT NULL,
  style_sheet text,
  script text,
  post_signature text,
  format varchar(8) DEFAULT NULL,
  privacy smallint NOT NULL,
  owner_id integer NOT NULL,
  view_count integer NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (alias)
);

CREATE TABLE emailsubscribers (
  id varchar(8) NOT NULL,
  collection_id integer NOT NULL,
  user_id integer DEFAULT NULL,
  email varchar(255) DEFAULT NULL,
  subscribed timestamptz NOT NULL,
  token varchar(16) NOT NULL,
  confirmed boolean NOT NULL DEFAULT false,
  allow_export boolean NOT NULL DEFAULT false,
  PRIMARY KEY (id),
  CONSTRAINT eu_coll_email UNIQUE (collection_id, email),
  CONSTRAINT eu_coll_user UNIQUE (collection_id, user_id)
);

CREATE TABLE oauth_client_states (
  state varchar(255) NOT NULL,
  used boolean NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  provider varchar(24) NOT NULL DEFAULT '',
  client_id varchar(128) NOT NULL DEFAULT '',
  attach_user_id integer DEFAULT NULL,
  invite_code varchar(6) DEFAULT NULL,
  UNIQUE (state)
);

-- access_token is text, as MySQL's has been since V11.
CREATE TABLE oauth_users (
  user_id integer NOT NULL,
  remote_user_id varchar(128) NOT NULL,
  provider varchar(24) NOT NULL DEFAULT '',
  client_id varchar(128) NOT NULL DEFAULT '',
  access_token text DEFAULT NULL,
  CONSTRAINT oauth_users_uk UNIQUE (user_id, provider, client_id)
);

CREATE TABLE password_resets (
  user_id integer NOT NULL,
  token varchar(32) NOT NULL,
  used boolean NOT NULL DEFAULT false,
  created timestamptz NOT NULL,
  PRIMARY KEY (token)
);

CREATE TABLE post_images (
  id varchar(6) NOT NULL,
  owner_id integer NOT NULL,
  post_id varchar(16) DEFAULT NULL,
  sha256 varchar(64) NOT NULL,
  path varchar(255) NOT NULL,
  filename varchar(255) NOT NULL,
  mime varchar(64) NOT NULL,
  size integer NOT NULL,
  created timestamptz NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT pi_owner_sum UNIQUE (owner_id, sha256),
  CONSTRAINT pi_path UNIQUE (path)
);

CREATE INDEX post_images_post_id ON post_images (post_id);

-- privacy is a bit field and pinned_position a small number, so both are
-- smallint. rtl is a nullable flag. V9's (owner_id, id) index is not
-- repeated: the UNIQUE constraint on the same columns already provides it.
CREATE TABLE posts (
  id varchar(16) NOT NULL,
  slug varchar(100) DEFAULT NULL,
  modify_token varchar(32) DEFAULT NULL,
  text_appearance varchar(4) NOT NULL DEFAULT 'norm',
  language varchar(2) DEFAULT NULL,
  rtl boolean DEFAULT NULL,
  privacy smallint NOT NULL,
  owner_id integer DEFAULT NULL,
  collection_id integer DEFAULT NULL,
  pinned_position smallint DEFAULT NULL,
  created timestamptz NOT NULL DEFAULT now(),
  updated timestamptz NOT NULL DEFAULT now(),
  view_count integer NOT NULL,
  title varchar(160) NOT NULL,
  content text NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT id_slug UNIQUE (collection_id, slug),
  UNIQUE (owner_id, id)
);

CREATE INDEX privacy_id ON posts (privacy, id);

CREATE INDEX posts_get_collection_index ON posts (collection_id, pinned_position, created);

CREATE TABLE publishjobs (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  post_id varchar(16) NOT NULL,
  action varchar(16) NOT NULL,
  delay smallint NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE remote_likes (
  post_id varchar(16) NOT NULL,
  remote_user_id integer NOT NULL,
  created timestamptz NOT NULL,
  PRIMARY KEY (post_id, remote_user_id)
);

CREATE TABLE remotefollows (
  collection_id integer NOT NULL,
  remote_user_id integer NOT NULL,
  created timestamptz NOT NULL,
  PRIMARY KEY (collection_id, remote_user_id)
);

CREATE TABLE remoteuserkeys (
  id varchar(255) NOT NULL,
  remote_user_id integer NOT NULL,
  public_key bytea NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT follower_id UNIQUE (remote_user_id)
);

-- The URL-like columns are text: remote servers send values longer than 255.
CREATE TABLE remoteusers (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  actor_id text NOT NULL,
  inbox text NOT NULL,
  shared_inbox text NOT NULL,
  url text DEFAULT NULL,
  handle text DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE (actor_id)
);

CREATE TABLE userattributes (
  user_id integer NOT NULL,
  attribute varchar(64) NOT NULL,
  value varchar(255) NOT NULL,
  PRIMARY KEY (user_id, attribute)
);

-- The primary keys here and on usersinvited are the ones migration V1
-- creates. schema.sql and sqlite.sql never had them.
CREATE TABLE userinvites (
  id varchar(6) NOT NULL,
  owner_id integer NOT NULL,
  max_uses smallint DEFAULT NULL,
  created timestamptz NOT NULL,
  expires timestamptz DEFAULT NULL,
  inactive boolean NOT NULL,
  PRIMARY KEY (id)
);

-- email holds encrypted bytes, so it is bytea.
CREATE TABLE users (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  username varchar(100) NOT NULL,
  password varchar(60) NOT NULL,
  email bytea DEFAULT NULL,
  created timestamptz NOT NULL DEFAULT now(),
  status integer NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE (username)
);

CREATE TABLE usersinvited (
  invite_id varchar(6) NOT NULL,
  user_id integer NOT NULL,
  PRIMARY KEY (invite_id, user_id)
);
