/*
 * Copyright © 2019 Musing Studio LLC.
 *
 * This file is part of WriteFreely.
 *
 * WriteFreely is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License, included
 * in the LICENSE file in this source code package.
 */

package migrations

import (
	"fmt"
)

// Each helper returns the SQL for one engine and panics on a driver it does
// not know, so a new engine can never fall through to MySQL SQL. Postgres
// follows the type mapping in postgres.sql: CHAR becomes VARCHAR because
// Postgres pads CHAR(n) with spaces, flags are BOOLEAN, and timestamps are
// TIMESTAMPTZ.

// TODO: use now() from writefreely pkg
func (db *datastore) now() string {
	switch db.driverName {
	case driverSQLite:
		return "strftime('%Y-%m-%d %H:%M:%S','now')"
	case driverMySQL, driverPostgres:
		return "NOW()"
	}
	panic(unknownDriver("now", db.driverName))
}

func (db *datastore) typeInt() string {
	switch db.driverName {
	case driverSQLite, driverPostgres:
		return "INTEGER"
	case driverMySQL:
		return "INT"
	}
	panic(unknownDriver("typeInt", db.driverName))
}

func (db *datastore) typeSmallInt() string {
	switch db.driverName {
	case driverSQLite:
		return "INTEGER"
	case driverMySQL, driverPostgres:
		return "SMALLINT"
	}
	panic(unknownDriver("typeSmallInt", db.driverName))
}

// typeTinyInt is for small numbers. A yes/no column wants typeBool.
// Postgres has no TINYINT, so it gets SMALLINT.
func (db *datastore) typeTinyInt() string {
	switch db.driverName {
	case driverSQLite:
		return "INTEGER"
	case driverMySQL:
		return "TINYINT"
	case driverPostgres:
		return "SMALLINT"
	}
	panic(unknownDriver("typeTinyInt", db.driverName))
}

func (db *datastore) typeText() string {
	switch db.driverName {
	case driverSQLite, driverMySQL, driverPostgres:
		return "TEXT"
	}
	panic(unknownDriver("typeText", db.driverName))
}

// typeChar is a fixed-length string on MySQL. Postgres gets VARCHAR: its
// CHAR(n) pads shorter values with spaces, and they come back padded.
func (db *datastore) typeChar(l int) string {
	switch db.driverName {
	case driverSQLite:
		return "TEXT"
	case driverMySQL:
		return fmt.Sprintf("CHAR(%d)", l)
	case driverPostgres:
		return fmt.Sprintf("VARCHAR(%d)", l)
	}
	panic(unknownDriver("typeChar", db.driverName))
}

func (db *datastore) typeVarChar(l int) string {
	switch db.driverName {
	case driverSQLite:
		return "TEXT"
	case driverMySQL, driverPostgres:
		return fmt.Sprintf("VARCHAR(%d)", l)
	}
	panic(unknownDriver("typeVarChar", db.driverName))
}

func (db *datastore) typeVarBinary(l int) string {
	switch db.driverName {
	case driverSQLite:
		return "BLOB"
	case driverMySQL:
		return fmt.Sprintf("VARBINARY(%d)", l)
	case driverPostgres:
		return "BYTEA"
	}
	panic(unknownDriver("typeVarBinary", db.driverName))
}

func (db *datastore) typeBool() string {
	switch db.driverName {
	case driverSQLite:
		return "INTEGER"
	case driverMySQL:
		return "TINYINT(1)"
	case driverPostgres:
		return "BOOLEAN"
	}
	panic(unknownDriver("typeBool", db.driverName))
}

func (db *datastore) typeDateTime() string {
	switch db.driverName {
	case driverSQLite, driverMySQL:
		return "DATETIME"
	case driverPostgres:
		return "TIMESTAMPTZ"
	}
	panic(unknownDriver("typeDateTime", db.driverName))
}

func (db *datastore) typeIntPrimaryKey() string {
	switch db.driverName {
	case driverSQLite:
		// From docs: "In SQLite, a column with type INTEGER PRIMARY KEY is an alias for the ROWID (except in WITHOUT
		// ROWID tables) which is always a 64-bit signed integer."
		return "INTEGER PRIMARY KEY"
	case driverMySQL:
		return "INT AUTO_INCREMENT PRIMARY KEY"
	case driverPostgres:
		// BY DEFAULT rather than ALWAYS, so that a data copy can insert
		// explicit ids and then move the sequence on with setval.
		return "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
	}
	panic(unknownDriver("typeIntPrimaryKey", db.driverName))
}

func (db *datastore) collateMultiByte() string {
	switch db.driverName {
	case driverSQLite, driverPostgres:
		return ""
	case driverMySQL:
		return " COLLATE utf8_bin"
	}
	panic(unknownDriver("collateMultiByte", db.driverName))
}

func (db *datastore) engine() string {
	switch db.driverName {
	case driverSQLite, driverPostgres:
		return ""
	case driverMySQL:
		return " ENGINE = InnoDB"
	}
	panic(unknownDriver("engine", db.driverName))
}

// after places a new column after colName on MySQL. Other engines always
// append it, which is harmless as long as nothing selects `*`.
func (db *datastore) after(colName string) string {
	switch db.driverName {
	case driverSQLite, driverPostgres:
		return ""
	case driverMySQL:
		return " AFTER " + colName
	}
	panic(unknownDriver("after", db.driverName))
}

func unknownDriver(fn, driverName string) string {
	return fmt.Sprintf("migrations.%s: unknown database driver %q", fn, driverName)
}
